collections:
    posts:
        experience: blog-post
        fields:
            body: body
            date: date
            description: description
            draft: draft
            featured: featured
            heroImage: heroImage
            tags: tags
            title: title
            updatedDate: updatedDate
        references:
            tags: tags
    notes:
        experience: note
        fields:
            body: body
            date: date
            draft: draft
            images: images
            tags: tags
        references:
            tags: tags
    tags:
        experience: tag
        fields:
            description: description
            name: name
